# Generated by Django 5.2.1 on 2025-06-03 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='stores.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('image', models.ImageField(upload_to='store')),
                ('photoOne', models.ImageField(blank=True, null=True, upload_to='store')),
                ('photoTwo', models.ImageField(blank=True, null=True, upload_to='store')),
                ('photoThree', models.ImageField(blank=True, null=True, upload_to='store')),
                ('photFour', models.ImageField(blank=True, null=True, upload_to='store')),
                ('is_active', models.BooleanField(default=True)),
                ('in_stock', models.IntegerField()),
                ('product_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.category')),
            ],
        ),
    ]
