# Generated by Django 5.2.1 on 2025-06-04 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_cart_cartproduct_orderproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='Total',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='Total',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='photFour',
            new_name='photoFour',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
