# Generated by Django 5.2.1 on 2025-06-04 23:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_rename_total_cartproduct_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
