# Generated by Django 5.2.1 on 2025-06-04 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
