# Generated by Django 5.2.1 on 2025-06-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
