# Generated by Django 5.2.1 on 2025-06-04 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_remove_product_product_id'),
    ]

    operations = [
    ]
