# Generated by Django 5.2.1 on 2025-06-05 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='Amout',
        ),
    ]
